# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-15 15:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ace', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aceconfig',
            name='email_to',
        ),
    ]
