# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-15 18:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ace', '0005_aceconfig_email_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='object_id',
            field=models.CharField(editable=False, max_length=30, null=True),
        ),
    ]
