# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-27 09:09
from __future__ import unicode_literals

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('ace', '0006_log_object_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
            ],
            options={
                'ordering': ('first_name',),
                'proxy': True,
                'indexes': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='historicalphone',
            name='user',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ace.Person'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ace.Person', verbose_name='Usu\xe1rio'),
        ),
        migrations.AlterField(
            model_name='phoneownership',
            name='active',
            field=models.BooleanField(default=True, editable=False, verbose_name='Ativo(a)'),
        ),
        migrations.AlterField(
            model_name='phoneownership',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ace.Person', verbose_name='Usu\xe1rio'),
        ),
    ]
